### ISSUE TITLE
Failure to require files on my local filesystem

### ISSUE THREAD

**Issue by ggoodman** [matthewfl/node-host#2] opened 2010-11-30 15:09 UTC
I have saved a copy of node-router.js to my local filesystem under that same name.  Attempts to include that file in a second file, test.js have all failed. It seems that require() is silently returning null.

**Comment by matthewfl** [comment] 2010-12-01 04:20
I know there is a problem with searching for the module like how it is done in node, and thus exact file names must be used.
From testing just now it seems that if you do not have a ./ in the require statement it will not throw any errors and just return null, but if you have ./wrong_file_name it will throw an error that the file is not found.

For now require('./node-router.js') should work

Note: that for you local file system it will always require a ./ (or similar) in the require statement, the issue is that it is not failing when the name is wrong for the built in modules

**Comment by ggoodman** [comment] 2010-12-01 12:41
Hey Matthew, I've put together a little test case to illustrate my problem.

```
var http = require('http');

http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.write("./node-router.js:\t" + (typeof require('./node-router.js')) + "\n");
  res.write("./node-router:\t" + (typeof require('./node-router')) + "\n");
  res.write("node-router.js:\t" + (typeof require('node-router.js')) + "\n");
  res.write("node-router:\t" + (typeof require('node-router')) + "\n");
  res.end('');
}).listen();
```

Results in the following:

```
./node-router.js:   undefined
./node-router:  undefined
node-router.js: undefined
node-router:    undefined
```

**Comment by matthewfl** [comment] 2010-12-01 15:20
I did see your spicific problem and I will be working on a fix, but when I save the result of require to a variable I get a different result where the first two work when node-router is saved as node-router and node-router.js.
http://jsapp.us/s/45
This is just a workaround for now, and I will be trying to find the problem.

**Comment by matthewfl** [comment] 2010-12-04 07:59
This issue should be fixed now and live on the server.

**Closed as completed by matthewfl** 2010-12-04 07:59 UTC
Labels: Sandbox
